name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/Health-Record-System

            git pull origin main

            # Backend
            cd backend
            npm install
            npx prisma generate
            pm2 restart backend

            # Frontend
            cd ../frontend
            npm install
            npm run build
            pm2 restart frontend